
name: pull_request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">= 1.19.0"
      - name: test
        run: go test -v ./...
      - name: build docker image
        run: go build -o outstanding-prs . && docker build -t cuotos/outstanding-prs .
      
      - id: scan
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: cuotos/outstanding-prs
          annotations: true
